extends RichTextLabel

func _process(_delta: float) -> void:
	text = ""

	push_table(2)
	push_cell()
	append_text("Current Car")
	pop()
	push_cell()
	append_text(AACCGlobal.car.name)
	pop()
	pop()
	append_text("\n")

	push_table(2)
	push_cell()
	append_text("Inputs")
	pop()
	push_cell()
	append_text("Values")
	pop()
	for input: String in AACCGlobal.car.inputs.keys():
		push_cell()
		append_text(input)
		pop()
		push_cell()
		append_text(str(AACCGlobal.car.get_input(input)))
		pop()
	pop()
	append_text("\n")

	push_table(2)
	push_cell()
	append_text("Forces")
	pop()
	push_cell()
	append_text("Values")
	pop()
	for force: String in AACCGlobal.car.forces.keys():
		push_cell()
		append_text(force)
		pop()
		push_cell()
		append_text(str(AACCGlobal.car.get_force(force).force))
		pop()
	pop()
	append_text("\n")

	push_table(2)
	push_cell()
	append_text("Torques")
	pop()
	push_cell()
	append_text("Values")
	pop()
	for torque: String in AACCGlobal.car.torques.keys():
		push_cell()
		append_text(torque)
		pop()
		push_cell()
		append_text(str(AACCGlobal.car.get_torque(torque).torque))
		pop()
	pop()
	append_text("\n")

	push_table(2)
	push_cell()
	append_text("Params")
	pop()
	push_cell()
	append_text("Values")
	pop()
	for param: String in AACCGlobal.car.params.keys():
		push_cell()
		append_text(param)
		pop()
		push_cell()
		append_text(str(AACCGlobal.car.get_param(param)))
		pop()
	pop()
